
services:
  # --- DATABASE (PostgreSQL) ---
  rukun-jaya-db:
    image: postgres:15-alpine
    container_name: rukun-jaya-db
    restart: always
    environment:
      POSTGRES_DB: rukun_jaya_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_rahasia
    ports:
      - "5432:5432"
    volumes:  
      - pgdata:/var/lib/postgresql/data

   # --- BACKEND (Express.js + Prisma) ---
  rukun-jaya-backend:
    build: 
      context: ../be-rukun-jaya  # Merujuk ke folder backend
      dockerfile: Dockerfile     # Menggunakan Dockerfile yang baru kita buat
    container_name: rukun-jaya-backend
    ports:
      - "5000:5000"
    environment:
      # URL Database menunjuk ke service 'rukun-jaya-db' (PostgreSQL container)
      - DATABASE_URL=postgresql://postgres:password_rahasia@rukun-jaya-db:5432/rukun_jaya_db?schema=public
      - JWT_SECRET=rahasia_super_aman # Ganti dengan secret Anda
      - PORT=5000
    depends_on:
      - rukun-jaya-db


  # --- FRONTEND (Next.js) ---
  rukun-jaya-frontend:
    build:
      context: ../fe-rukun-jaya
      dockerfile: dockerfile
    container_name: rukun-jaya-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ../fe-rukun-jaya/.env
    restart: unless-stopped
    depends_on:
      - rukun-jaya-backend

# Deklarasi Volume untuk Penyimpanan Data Database Permanen
volumes:
  pgdata: